# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.155.2+26.1.2

# Mod Properties
mod_version = 1.2.1
maven_group = com.github.nyuppo
archives_base_name = hotbarcycle

# Config
cloth_config = 26.1.154
mod_menu = 18.0.0

# Compat
inventory_profiles_next = 26.1-2.3.5
